# Generated by Django 3.2.12 on 2022-04-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='Img',
            field=models.ImageField(default='ddfdf', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
